/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32g4xx.h"
#include "stm32g4xx_gpio_driver.h"


void delay()
{
	for(uint32_t i=0;i<100000; i++);
}


int main(void)
{

	GPIO_Handel_t GpioLed;
	GPIO_Handel_t GpioBut;



/*
*
* GPIO Push Pull Configuration
*
*/

	GpioLed.pGPIOx = GPIOC;
	GpioLed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_6;
	GpioLed.GPIO_PinConfig.GPIO_PinMode = GPIO_OUTPUT_MODE;
	GpioLed.GPIO_PinConfig.GPIO_PinSpeed = GPIO_HIGH_SPEED;
	GpioLed.GPIO_PinConfig.GPIO_PinPuPDControl = GPIO_NOPUPD;
	GpioLed.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;

	GPIO_PeriClkCtrl(GPIOC, ENABLE);
	GPIO_Init(&GpioLed);

/*
*
* GPIO Open Drain Configuration
*
*/
	/*
	GpioLed.pGPIOx = GPIOC;
	GpioLed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_6;
	GpioLed.GPIO_PinConfig.GPIO_PinMode = GPIO_OUTPUT_MODE;
	GpioLed.GPIO_PinConfig.GPIO_PinSpeed = GPIO_HIGH_SPEED;
	GpioLed.GPIO_PinConfig.GPIO_PinPuPDControl = GPIO_PU;
	GpioLed.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_OD;
    */

/*
*
* GPIO Input button
*
*/

	GpioBut.pGPIOx = GPIOD;
	GpioBut.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_12;
	GpioBut.GPIO_PinConfig.GPIO_PinMode = GPIO_OUTPUT_MODE;
	GpioBut.GPIO_PinConfig.GPIO_PinSpeed = GPIO_HIGH_SPEED;
	GpioBut.GPIO_PinConfig.GPIO_PinPuPDControl = GPIO_NOPUPD;

	GPIO_PeriClkCtrl(GPIOD, ENABLE);
	GPIO_Init(&GpioBut);

	while(1)
	{
		if(GPIO_ReadPIN(GPIOD, GPIO_PIN_NO_12) == BTN_PRESSED)
		{
			GPIO_WritePIN(GPIOC, 6, GPIO_PIN_SET);
		}
		else
		{
			GPIO_WritePIN(GPIOC, 6, GPIO_PIN_RESET);
		}

	}
}
